### PR TITLE
Error handling

### LINKED ISSUE #41: Error handling
Ensure error handling for the following:
- Invalid commands
- Invalid arguments
- Incorrect number of arguments provided
- Invalid argument format

List is non-exhaustive.

Tidy up code where necessary.

### PR DESCRIPTION
**Pull request by sean6369**
### New Exception Types
- **`InvalidCommandSyntaxException`** - Thrown when command syntax is malformed or incomplete (e.g., missing required flags, wrong parameter order, legacy syntax usage)
- **`InvalidDateException`** - Thrown when date strings cannot be parsed, specifically for YYYY-MM-DD format validation in deadline parsing
- **`InvalidFilenameException`** - Thrown when export filenames don't meet validation criteria (invalid characters, missing .txt extension, platform-specific constraints)
- **`InvalidIndexFormatException`** - Thrown when task/project indices are non-numeric or malformed (replaces generic NumberFormatException with user-friendly messages)
- **`EmptyTaskListException`** - Thrown when operations are attempted on empty task lists (filtering, sorting, listing, exporting)

### Centralized Validation
- `ArgumentParser.validateProjectIndex()` - centralized project index validation
- `CommandValidator.validateAndParseDate()` - centralized date parsing with `InvalidDateException`
- `CommandParser.parseIndexOrNull()` - throws `InvalidIndexFormatException` for non-numeric indices

### API Contract Changes
- `TaskList`, `Project`, `ProjectList` methods now validate indices and throw `IndexOutOfRangeException`
- `Project` constructor rejects null/empty names
- `ConsoleUi.showAddedTask()` now declares `throws IndexOutOfRangeException`
- `CommandHandler` separates user errors (`FlowCLIException`) from unexpected errors

### Export Improvements
- `ExportCommandHandler` adds filename validation with `InvalidFilenameException`
- `TaskExporter` provides detailed file write error messages (permission, disk space, locked files, etc.)
- Stricter export syntax validation, rejects legacy formats

### UI & Testing
- Added `ConsoleUi.showError()` and `showUnexpectedError()` helpers
- Updated tests to match new exception signatures and API contracts
- Enhanced logging in command classes

closes #41

### CODE REVIEW

File: src/main/java/seedu/flowcli/commands/core/InteractivePromptHandler.java [hunk 1]
```diff
@@ -21,7 +24,7 @@ public class InteractivePromptHandler {
      * input scanner.
      *
      * @param projects The project list for accessing available projects
-     * @param scanner The scanner for reading user input
+     * @param scanner  The scanner for reading user input
```
Comment (zeeeing) [inline src/main/java/seedu/flowcli/commands/core/InteractivePromptHandler.java]: why you add additional whitespace?

File: src/main/java/seedu/flowcli/ui/ConsoleUi.java [hunk 2]
```diff
@@ -328,4 +340,36 @@ private String getMotivationalMessage(double percentage) {
...
+        System.out.println("Please try again or contact support if the problem persists.");
+        printLine();
+    }
+
+    /**
+     * Displays a generic unexpected error message to the user with consistent formatting.
+     */
+    public void showUnexpectedError() {
+        printLine();
+        System.out.println("An unexpected error occurred. Please try again or contact " +
```
Comment (zeeeing) [inline src/main/java/seedu/flowcli/ui/ConsoleUi.java]: same here

File: src/main/java/seedu/flowcli/unused/LegacyExportSupport.java
Comment (zeeeing) [inline src/main/java/seedu/flowcli/unused/LegacyExportSupport.java]: its a legacy file, don't change it.

**Review by zeeeing — CHANGES_REQUESTED** [review]

**Review by Yxiang-828 — APPROVED** [review]
looks good to me, able to merge.

**Review by Yxiang-828 — CHANGES_REQUESTED** [review]
update: some bugs unnoticed in here have been fixed in my pull request, and `list` interactive mode has been updated, can you merge with it first? thanks
